### ISSUE TITLE
Video Curtain does not show video file

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#30]
needs investigation and perhaps fixing

**Comment by julrich** [comment]
This was not working, because of a missing whitelist entry for `media-src` (which affects which domains can be used when loading media files, in addition to the current domain) and `a.storyblok.com` (where CMS assets like images and videos are hosted).

See: https://github.com/kickstartDS/dr-hubert-website/commit/63639090ae0442aedcc6a949c787d1185ddd02ac
